# For information on each parameter see https://guidelines.quintoandar.com.br/#/checklist/?id=parameters
apiVersion: quintoandar.com.br/checklist/v2
metadata:
  name: butterfree
spec:
  docs: true
  description: A solution for Feature Stores.
  lifecycle: production
  ownership:
    line: tech_platform
    team: data_products_mlops
    owner: otavio.cals@quintoandar.com.br

  libraries:
    - name: butterfree
      path: https://quintoandar.github.io/python-package-server/
      description: A lib to build Feature Stores.
      registries:
        - github-packages
      type: common-usage
      tier: T0
