clone:
  git:
    image: plugins/git

pipeline:
  install: &install
    image: rappdw/docker-java-python
    commands:
      - make drone-install

  style-check:
    <<: *install
    commands:
      - PYTHONPATH=./pip/deps make style-check
    group: tests
    when:
      event: push

  quality-check:
    <<: *install
    commands:
      - PYTHONPATH=./pip/deps make quality-check
    group: tests
    when:
      event: push

  tests-python3.6:
    <<: *install
    commands:
      - PYTHONPATH=./pip/deps make tests
    group: tests
    when:
      event: push

  version:
    image: python:3.6
    commands:
      - git clone https://github.com/quintoandar/python-package-server.git --quiet
      - make -s check-version
    when:
      event: [pull_request, push, tag]
      branch: master

  package:
    image: python:3.6
    commands:
      - make package
    when:
      branch: [master]
      event: [tag]

  release:
    image: plugins/github-release
    pull: true
    files: dist/*
    title: .version
    secrets:
      - source: github_access_token
        target: github_token
    when:
      branch: [master]
      event: [tag]

  publish:
    image: python:3.6
    commands:
      - make publish
    secrets:
      - source: github_access_token
        target: github_token
    when:
      branch: [master]
      event: [tag]

  sonar-preview:
    image: newtmitch/sonar-scanner
    commands:
      - |-
        sonar-scanner \
          -Dsonar.projectName=Butterfree \
          -Dsonar.projectKey=${DRONE_REPO_NAME} \
          -Dsonar.projectBaseDir=. \
          -Dsonar.sources=./butterfree \
          -Dsonar.sourceEncoding=UTF-8 \
          -Dsonar.analysis.mode=preview \
          -Dsonar.github.pullRequest=${DRONE_PULL_REQUEST} \
          -Dsonar.github.repository=${DRONE_REPO_OWNER}/${DRONE_REPO_NAME} \
          -Dsonar.github.oauth=$${GITHUB_ACCESS_TOKEN} \
          -Dsonar.host.url=https://sonar.quintoandar.com.br \
          -Dsonar.login=user \
          -Dsonar.password=$${SONAR_PASSWORD}
    secrets: [ sonar_password, github_access_token ]
    when:
      event: pull_request
      branch: [ master ]

  ###
  ### PRODUCTION
  ###
  sonar-report:
    image: newtmitch/sonar-scanner
    commands:
      - |-
        sonar-scanner \
          -Dsonar.projectName=Butterfree \
          -Dsonar.projectKey=${DRONE_REPO_NAME} \
          -Dsonar.projectBaseDir=. \
          -Dsonar.sources=./butterfree \
          -Dsonar.python.coverage.reportPath=coverage.xml \
          -Dsonar.sourceEncoding=UTF-8 \
          -Dsonar.tests=./tests \
          -Dsonar.host.url=https://sonar.quintoandar.com.br \
          -Dsonar.projectKey=${DRONE_REPO_NAME} \
          -Dsonar.login=user \
          -Dsonar.password=$${SONAR_PASSWORD}
    secrets: [ sonar_password, github_access_token ]
    when:
      event: push
      branch: [ master ]

  notify:
    image: plugins/slack
    channel: data-products-reports
    secrets: [ slack_webhook ]
    when:
      event: [ push ]
      branch: [ forno, master ]
      status: [ success, failure ]
