"""Feature entity."""

import warnings
from typing import Any, List, Optional

from pyspark.sql import DataFrame
from pyspark.sql.functions import col

from butterfree.constants import DataType
from butterfree.metadata.feature_metadata import FeatureMetadata
from butterfree.transform.transformations import (
    AggregatedTransform,
    CustomTransform,
    SparkFunctionTransform,
    SQLExpressionTransform,
    StackTransform,
    TransformComponent,
)
from butterfree.transform.transformations.h3_transform import H3HashTransform
from butterfree.transform.utils import Window


class Feature:
    """Defines a Feature.

    A Feature is the result of a transformation over one (or more) data columns
    over an input dataframe. Transformations can be as simple as renaming,
    casting types, mathematical expressions or complex functions/models.

    Attributes:
        name: feature name.
            Can be use by the transformation to derive multiple output columns.
        description: brief explanation regarding the feature.
        dtype: data type for the output columns of this feature.
        from_column: original column to build feature.
            Used when there is transformation or the transformation has no
            reference about the column to use for.
        transformation: transformation that will be applied to create this
            feature.

    """

    def __init__(
        self,
        name: str,
        description: str,
        dtype: Optional[DataType] = None,
        from_column: Optional[str] = None,
        transformation: Optional[TransformComponent] = None,
    ) -> None:
        self.name = name
        self.description = description
        self.transformation = transformation
        self.dtype = dtype
        self.from_column = from_column

    @property
    def dtype(self) -> DataType:
        """Attribute dtype getter."""
        return self.__dtype

    @dtype.setter
    def dtype(self, value: DataType) -> None:
        if (
            not (
                isinstance(self.transformation, AggregatedTransform)
                or isinstance(self.transformation, SparkFunctionTransform)
            )
            and value is None
        ):
            raise ValueError(
                "dtype can't be None, except if the transformation is "
                "AggregatedTransform or SparkFunctionTransform"
            )

        if value is not None and not isinstance(value, DataType):
            raise ValueError("dtype must be a DataType.")

        self.__dtype = value

    @property
    def from_column(self) -> Any:
        """Attribute from_column getter."""
        return self.__from_column  # type: ignore

    @from_column.setter
    def from_column(self, value: str) -> None:
        if (
            isinstance(self.transformation, CustomTransform)
            or isinstance(self.transformation, SQLExpressionTransform)
            or isinstance(self.transformation, H3HashTransform)
            or isinstance(self.transformation, StackTransform)
        ) and value is not None:
            raise ValueError(
                f"from_column parameter doesn't need to be declared, "
                f"the column name {value} would be overwritten with "
                f"another name."
            )

        if value is not None and not isinstance(value, str):
            raise ValueError("from_column must be a string.")

        self.__from_column = value

    @property
    def transformation(self) -> TransformComponent:
        """Attribute transformation getter."""
        return self.__transformation

    @transformation.setter
    def transformation(self, value: TransformComponent) -> None:
        self.__transformation = value

        if value is not None:
            self.__transformation.parent = self

    def get_output_columns(self) -> List[str]:
        """Get output columns that will be generated by this feature engineering.

        Returns
            Output columns names.
        """
        if self.transformation is not None:
            return self.transformation.output_columns
        return [self.name]

    def transform(self, dataframe: DataFrame) -> DataFrame:
        """Performs a transformation to the feature pipeline.

        Args:
            dataframe: input dataframe for the transformation.

        Returns:
            Transformed dataframe.
        """
        if self.transformation:
            return self.transformation.transform(dataframe)

        if self.from_column:
            if self.name in dataframe.columns:
                warnings.warn(
                    f"The column name {self.name} "
                    "already exists in the dataframe and "
                    "will be overwritten with another column."
                )

            dataframe = dataframe.withColumn(self.name, col(self.from_column))

        if self.dtype:
            dataframe = dataframe.withColumn(
                self.name, col(self.name).cast(self.dtype.spark)
            )
        return dataframe

    def _build_feature_column_name(
        self,
        base_name: str,
        pivot_value: Optional[Any] = None,
        window: Optional[Window] = None,
    ) -> str:
        """Helper to build the feature column name based on pivot and window."""
        name = base_name
        if pivot_value is not None:
            name = f"{pivot_value}_{name}"
        if window is not None:
            name = f"{name}_{window.get_name()}"
        return name

    def build_metadata(
        self,
        pivot_value: Optional[Any] = None,
        window: Optional[Window] = None,
    ) -> List[FeatureMetadata]:
        """Build the metadata for the feature.

        Args:
            pivot_value: Optional pivot value for naming.
            window: Optional window for naming.

        Returns:
            A list of FeatureMetadata objects.
        """
        metadata_list = []
        output_columns = self.get_output_columns()

        if isinstance(
            self.transformation, (AggregatedTransform, SparkFunctionTransform)
        ):
            # For these transformations, data types come from the
            # transformation's functions and names are based on the function
            # names combined with feature name.
            for func_idx, function_obj in enumerate(self.transformation.functions):
                # output_columns from get_output_columns already includes
                # the function name part e.g., feature_name__avg,
                # feature_name__sum. We need to reconstruct the name with
                # pivot and window if they exist.
                base_output_name = output_columns[func_idx]

                # Check if the base_output_name already contains self.name
                # to avoid duplication like feature_name_feature_name__avg
                if self.name in base_output_name:
                    # This typically happens when transformation.output_columns
                    # are like ["feature_name__avg"]. We want the part after
                    # the feature name and double underscore.
                    func_specific_suffix = base_output_name.split(f"{self.name}__")[-1]
                    constructed_name_base = f"{self.name}__{func_specific_suffix}"
                else:
                    # This case might occur if get_output_columns returns
                    # just function names like ["avg"] or if the feature name
                    # is not part of the transformation output by default.
                    constructed_name_base = f"{self.name}__{base_output_name}"

                final_name = self._build_feature_column_name(
                    constructed_name_base, pivot_value, window
                )
                data_type = function_obj.data_type.name
                metadata_list.append(
                    FeatureMetadata(
                        name=final_name,
                        data_type=data_type,
                        description=self.description,
                        primary_key=False,
                    )
                )
        else:
            # For other features or features without complex transformations
            for col_name in output_columns:
                final_name = self._build_feature_column_name(
                    col_name, pivot_value, window
                )
                if self.dtype is None:
                    # This case should ideally be prevented by the dtype setter validation,
                    # but raising an error here provides an explicit check during metadata build.
                    raise ValueError(
                        f"Feature '{self.name}' (column: '{col_name}') must have a dtype defined "
                        "when not using AggregatedTransform or SparkFunctionTransform."
                    )
                data_type = self.dtype.name
                metadata_list.append(
                    FeatureMetadata(
                        name=final_name,
                        data_type=data_type,
                        description=self.description,
                        primary_key=False,
                    )
                )
        return metadata_list
