"""CustomTransform entity."""

from typing import Callable, List

from pyspark.sql import DataFrame

from butterfree.core.transform.transformations.transform_component import (
    TransformComponent,
)


class CustomTransform(TransformComponent):
    """Defines a Custom Transform.

    Attributes:
        transformer: function to use for transforming the dataframe
        **kwargs: kwargs for the transformer

    """

    def __init__(self, transformer: Callable, **kwargs):
        super().__init__()
        self.transformer = transformer
        self.transformer__kwargs = kwargs

    @property
    def transformer(self) -> Callable:
        """Function to use for transforming the dataframe."""
        return self._transformer

    @transformer.setter
    def transformer(self, method: Callable):
        if not method:
            raise ValueError("A method must be provided to CustomTransform")
        self._transformer = method

    @property
    def output_columns(self) -> List[str]:
        """Columns generated by transformation."""
        output_columns = [
            self._parent.from_column if self._parent.from_column else self._parent.name
        ]
        return output_columns

    def transform(self, dataframe: DataFrame) -> DataFrame:
        """Performs a transformation to the feature pipeline.

        Args:
            dataframe: input dataframe to be transformed.

        Returns:
            Transformed dataframe.

        """
        dataframe = self.transformer(
            dataframe, self.parent, **self.transformer__kwargs,
        )
        return dataframe
