"""SQL Expression Transform entity."""

from typing import List

from parameters_validation import non_blank
from pyspark.sql import DataFrame

from butterfree.core.transform.transformations.transform_component import (
    TransformComponent,
)


class SQLExpressionTransform(TransformComponent):
    """Defines an SQL Expression Transformation.

    Attributes:
        expression: SQL expression defined by the user.
    """

    def __init__(
        self, expression: non_blank(str),
    ):
        super().__init__()
        self.expression = expression

    @property
    def output_columns(self) -> List[str]:
        """Columns generated by the transformation."""
        return [self._parent.name]

    def transform(self, dataframe: DataFrame) -> DataFrame:
        """Performs a transformation to the feature pipeline.

        Args:
            dataframe: input dataframe.

        Returns:
            Transformed dataframe.

        """
        try:
            return dataframe.selectExpr(
                f"*", f"{self.expression} as {self._parent.name}"
            )
        except Exception as e:
            raise e
