"""Aggregated Transform entity."""

from typing import List

from parameters_validation import non_blank
from pyspark.sql import DataFrame, functions
from pyspark.sql.window import Window

from butterfree.core.transform.transform_component import TransformComponent


class AggregatedTransform(TransformComponent):
    """Defines an Aggregation.

    Attributes:
        aggregations: list containing the desired aggregations.
        windows: time windows.
        partition: partition definition.
        time_column: time column definition.
    """

    def __init__(
        self,
        aggregations: non_blank(List[str]),
        windows: non_blank(List[str]),
        partition: non_blank(str) = None,
        time_column: str = None,
    ):
        super().__init__()
        self.aggregations = aggregations
        self.windows = windows
        self.partition = partition
        self.time_column = time_column or "timestamp"

    __ALLOWED_AGGREGATIONS = {"avg": functions.avg, "std": functions.stddev_pop}
    __ALLOWED_WINDOWS = {
        ("second", "seconds"): 1,
        ("minute", "minutes"): 60,
        ("hour", "hours"): 3600,
        ("day", "days"): 86400,
        ("week", "weeks"): 604800,
        ("month", "months"): 2419200,
        ("year", "years"): 29030400,
    }

    @property
    def aggregations(self):
        """Returns the aggregations."""
        return self._aggregations

    @aggregations.setter
    def aggregations(self, value: List[str]):
        aggregations = []
        if not value:
            raise ValueError("Aggregations must not be empty.")
        for agg in value:
            if agg not in self.allowed_aggregations:
                raise KeyError(
                    f"{agg} is not supported. These are the allowed "
                    f"aggregations that you can use: "
                    f"{self.allowed_aggregations}"
                )
            aggregations.append(agg)
        self._aggregations = aggregations

    @property
    def allowed_aggregations(self):
        """Returns list of allowed aggregations."""
        return list(self.__ALLOWED_AGGREGATIONS.keys())

    @property
    def windows(self):
        """Returns the windows."""
        return self._windows

    @windows.setter
    def windows(self, windows: List[str]):
        if not windows:
            raise KeyError("Windows must not be empty.")
        if not isinstance(windows, List):
            raise KeyError(f"Windows must be a list.")
        for window in windows:
            if window.split()[1] not in self.allowed_windows:
                raise KeyError(
                    f"{window.split()[1]} is not supported. These are the allowed "
                    f"time windows that you can use: "
                    f"{self.allowed_windows}."
                )
            if len(window) == 0:
                raise KeyError(f"Windows must have one item at least.")
            if not all(int(window.split()[0]) >= 0 for window in windows):
                raise KeyError(f"{window} have negative element.")
        self._windows = windows

    @property
    def allowed_windows(self):
        """Returns list of allowed windows."""
        allowed_window_units = []
        for (i, j) in self.__ALLOWED_WINDOWS.keys():
            allowed_window_units.extend([i, j])
        return allowed_window_units

    @staticmethod
    def _window_definition(partition: str, time_column: str, window_span: int):
        w = (
            Window()
            .partitionBy(functions.col(partition))
            .orderBy(functions.col(time_column).cast("long"))
            .rangeBetween(-window_span, 0)
        )

        return w

    def _get_feature_name(self, aggregation, window_unit, window_size):
        return (
            f"{self._parent.name}__{aggregation}_over_{str(window_size)}_{window_unit}"
        )

    @property
    def output_columns(self):
        """Returns columns generated by transformation."""
        output_columns = []
        for aggregation in self._aggregations:
            for window_unit, window_sizes in self._windows.items():
                for window_size in window_sizes:
                    output_columns.append(
                        self._get_feature_name(aggregation, window_unit, window_size)
                    )

        return output_columns

    def transform(self, dataframe: DataFrame):
        """Performs a transformation to the feature pipeline.

        Args:
            dataframe: base dataframe.

        Returns:
            dataframe: transformed dataframe.
        """
        for aggregation in self._aggregations:
            for window_unit, window_sizes in self._windows.items():
                for window_size in window_sizes:
                    feature_name = self._get_feature_name(
                        aggregation=aggregation,
                        window_unit=window_unit,
                        window_size=window_size,
                    )
                    w = self._window_definition(
                        partition=f"{self.partition}",
                        time_column=f"{self.time_column}",
                        window_span=self.__ALLOWED_WINDOWS[window_unit] * window_size,
                    )
            for window in self._windows:
                name = self._get_alias(self._parent.alias)
                feature_name = (
                    f"{name}__{aggregation}_over_{window.split()[0]}"
                    f"_{window.split()[1]}"
                )
                w = self._window_definition(
                    partition=f"{self.partition}",
                    time_column=f"{self.time_column}",
                    window_span=self.get_window_span(
                        window_unit=window.split()[1],
                        window_size=int(window.split()[0]),
                    ),
                )

                dataframe = dataframe.select(functions.col("*")).withColumn(
                    feature_name,
                    self.__ALLOWED_AGGREGATIONS[aggregation](
                        f"{self._parent.name}"
                    ).over(w),
                )

        return dataframe
