"""Feature entity."""

from pyspark.sql import DataFrame

from butterfree.core.transform.transform_component import TransformComponent


class Feature:
    """Defines a Feature.

    Attributes:
        name: feature name.
        description: brief explanation regarding the feature.
        from_column: original column to build feature.
        transformation: transformation that will be applied to create this feature.
    """

    def __init__(
        self,
        name: str,
        description: str,
        from_column: str = None,
        transformation: TransformComponent = None,
    ):
        self.name = name
        self.from_column = from_column
        self.description = description
        self.transformation = transformation

    def get_output_columns(self):
        """Get output columns that will be generated by this feature engineering.

        :returns output_columns: output columns list.
        """
        if self.transformation is not None:
            return self.transformation.output_columns
        return [self.name]

    def transform(self, dataframe: DataFrame):
        """Performs a transformation to the feature pipeline.

        Args:
            dataframe: base dataframe.

        Returns:
            dataframe: transformed dataframe.
        """
        if self.transformation is None:
            return dataframe.withColumnRenamed(
                self.name, self.alias if self.alias else self.name
            )
        for transformation in self.transformations:
            return transformation.transform(dataframe)
