"""Feature entity."""

from typing import List

from pyspark.sql import DataFrame

from butterfree.core.transform.transform_component import TransformComponent


class Feature:
    """Defines a Feature, holds metadata and a set of transformations.

    Attributes:
        name: feature name.
        description: brief explanation regarding the feature.
        from_column: original column to build feature.
        transformation: transformation that will create the feature.

    """

    def __init__(
        self,
        name: str,
        description: str,
        from_column: str = None,
        transformation: TransformComponent = None,
    ):
        self.name = name
        self.from_column = from_column
        self.description = description
        self.transformation = transformation

    @property
    def transformation(self) -> TransformComponent:
        """Transformation that will create the feature."""
        return self._transformation

    @transformation.setter
    def transformation(self, transformation: TransformComponent):
        self._transformation = transformation
        if transformation is not None:
            self._transformation.parent = self

    def get_output_columns(self) -> List[str]:
        """Get columns that will be generated by this feature engineering.

        Returns:
            Output columns list.

        """
        if self.transformation is not None:
            return self.transformation.output_columns
        return [self.name]

    def transform(self, dataframe: DataFrame):
        """Performs a transformation to the feature pipeline.

        Args:
            dataframe: input dataframe.

        Returns:
            Transformed dataframe.

        """
        if self.transformation is None:
            return dataframe.withColumnRenamed(
                self.from_column, self.name if self.from_column else self.name
            )
        return self.transformation.transform(dataframe)
