name: Create Release Branch
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version name'
        required: true
jobs:
  createrelease:
    runs-on: ubuntu-latest

    steps:
    - name: Code checkout
      uses: actions/checkout@v2

    - name: Create release branch
      run: git checkout -b release/v${{ github.event.inputs.versionName }}

    - name: Initialize git config
      run: |
        git config user.name "GitHub Actions"
        git config user.email noreply@github.com

    - name: Change version
      run: printf 'version_name = "${{ github.event.inputs.versionName }}"\n' > app_versions.gradle

    - name: Update Changelog
      uses: thomaseizinger/keep-a-changelog-new-release@v1
      with:
        version: ${{ github.event.inputs.versionName }}

    - name: Commit changelog
      id: make-commit
      run: |
        git add app_versions.gradle
        git add CHANGELOG.md
        git commit –message "Prepare release ${{ github.event.inputs.versionName }}"
        echo "::set-output name=commit::$(git rev-parse HEAD)"

    - name: Push release branch
      run: git push origin release/v${{ github.event.inputs.versionName }}

    - name: Create PR in main
      uses: thomaseizinger/create-pull-request@1.0.0
      with:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       head: release/v${{ github.event.inputs.versionName }}
       base: main
       title: v${{ github.event.inputs.versionName }} into main
       reviewers: ${{ github.event.issue.user.login }}
       body: |
           Hi!
           This PR was created in response workflow running.
           I've updated the version name and code commit: ${{ steps.make-commit.outputs.commit }}.
