name: "CI"
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: rappdw/docker-java-python

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: make drone-install

    - name: Style Check
      run: PYTHONPATH=./pip/deps make style-check

    - name: Quality Check
      run: PYTHONPATH=./pip/deps make quality-check

    - name: Tests
      run: PYTHONPATH=./pip/deps make tests
