name: "CI"
on: [push]

jobs:
  Pipeline:
    runs-on: ubuntu-16.04
    container: rappdw/docker-java-python

    steps:
    - uses: actions/checkout@v2

    # Tests
    - name: Install dependencies
      run: make drone-install

    - name: Style check
      run: PYTHONPATH=./pip/deps make style-check

    - name: Quality check
      run: PYTHONPATH=./pip/deps make quality-check

    - name: Tests
      run: PYTHONPATH=./pip/deps make tests

    # Publish
    - name: Build package
      run: make package

    - name: Get version
      run: echo ::set-env name=version::$(grep __version__ setup.py | head -1 | cut -d \" -f2 | cut -d \' -f2)

    - name: v${{ env.version }}
      run: echo $version

    - name: Test Env2
      if: ${{ env.version == '0.10.3' }}
      run: echo Success!

    - name: Create release
      if: contains(github.ref, 'master')
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ env.version }}
        release_name: Release v${{ env.version }}

    - name: Publish release to pypi.org
      if: contains(github.ref, 'master')
      run: |
        pip install twine==3.1.1
        twine upload -u $PYPI_USERNAME -p $PYPI_PASSWORD --verbose dist/*
