on:
  push:
    branches:
      - staging

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target-branch: staging
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json

      - uses: actions/checkout@v4
        if: ${{ steps.release.outputs.release_created }}

      - uses: actions/setup-python@v5
        if: ${{ steps.release.outputs.release_created }}
        with:
          python-version: '3.9'

      - name: Install dependencies
        if: ${{ steps.release.outputs.release_created }}
        run: make ci-install

      - name: Build package
        if: ${{ steps.release.outputs.release_created }}
        run: make package

      - name: Publish release to pypi.org
        if: ${{ steps.release.outputs.release_created }}
        env:
          PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
          PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run:  PYTHONPATH=./pip/deps python -m twine upload -u $PYPI_USERNAME -p $PYPI_PASSWORD --verbose dist/*
