# This step is used only because we want to mark the runner-linter check as required
# for PRs to develop, but not for the merge queue to merge into develop,
# github does not have this functionality yet

name: 'Skip github-actions/runner-linter check at merge queue'

on:
  merge_group:

jobs:
  empty_job:
    name: 'github-actions/runner-linter'
    runs-on: github-actions-developers-runner
    steps:
      - name: Skip github-actions/runner-linter check at merge queue
        run: |
          echo "Done"
