name: "Publish Dev Package"
on:
  push:
    paths:
      - "setup.py"

jobs:
  Pipeline:
    if: github.ref == 'refs/heads/staging'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: microsoft

      - uses: vemonet/setup-spark@v1
        with:
          spark-version: '3.5.1'
          hadoop-version: '3'

      - name: Install dependencies
        run: make ci-install

      - name: Get version
        run: echo "version=$(grep __version__ setup.py | head -1 | cut -d \" -f2 | cut -d \' -f2 )" >> $GITHUB_ENV

      - name: Build package
        run: make package

      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.version }}
          release_name: Release ${{ env.version }}
          prerelease: true

      - name: Release already exist
        if: ${{ failure() }}
        run: echo Release already exist

      - name: Publish release to pypi.org
        if: ${{ success() }}
        env:
          PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
          PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: PYTHONPATH=./pip/deps python -m twine upload -u $PYPI_USERNAME -p $PYPI_PASSWORD --verbose dist/*
