name: "Test"
on:
  push:
    branches:
      - master
      - staging
      - hotfix/**
  pull_request:

jobs:
  Pipeline:
    runs-on: self-hosted
    container: quintoandar/python-3-7-java

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: make ci-install

    - name: Style check
      run: PYTHONPATH=./pip/deps make style-check

    - name: Quality check
      run: PYTHONPATH=./pip/deps make quality-check

    - name: Static Type check
      run: PYTHONPATH=./pip/deps make type-check

    - name: Tests
      run: PYTHONPATH=./pip/deps make tests
