name: "Test"
on:
  push:
    branches:
      - master
      - staging
      - hotfix/**
  pull_request:

jobs:
  Pipeline:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: temurin

    - uses: vemonet/setup-spark@v1
      with:
        spark-version: '3.4.3'
        hadoop-version: '3'

    - name: Install dependencies
      run: make ci-install

    - name: Style check
      run: PYTHONPATH=./pip/deps make style-check

    - name: Quality check
      run: PYTHONPATH=./pip/deps make quality-check

    - name: Static Type check
      run: PYTHONPATH=./pip/deps make type-check

    - name: Tests
      run: PYTHONPATH=./pip/deps make tests
